server:
  port: 8080
  https: false
  #cert_file: "/path/to/your/cert.pem"
  #key_file: "/path/to/your/key.pem"

webhooks:
  - type: "slack"
    config:
      url: "https://hooks.slack.com/services/TAAAAAA"  # using marketplace/-incoming-webhook  URL
  - type: "telegram"
    config:
      bot_token: "827..:AAAAA..." 
      chat_id: "88888888" 
  - type: "dingtalk"
    config:
      # dingtalk robot Webhook URL
      url: "https://oapi.dingtalk.com/robot/send?access_token=your_access_token"
      # Option: dingtalk webhook secret
      secret: "your_secret_key" 
      fields:
        - alertname
        - status
        - current_value
